//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_ParcialCorregido.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedidos
    {
        [Display(Name = "Codigo del Pedido")]
        public int PedidoId { get; set; }
        [Display(Name = "Codigo del Cliente")]
        public Nullable<int> ClienteId { get; set; }
        [Display(Name = "Monto del Pedido")]
        public decimal Monto { get; set; }
        [Display(Name = "Estado del Pedido")]
        public string Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
